Added print statements to destroy-retry commands to understand why it can't read my tfvars file
Currently if i run TF destroy in the nick-fields/retry action, it can't find my tfvars file:

 Error: Failed to read variables file
│
│ Given variables file terraform.tfvars does not exist.
╵
Error: Terraform exited with code 1.

______________________________
This doesn't happen when I run the command directly in the workflow without the retry action.